title: OpenAD Docs
description: Documentation for OpenAD, the Accelerated Discovery Open Toolkit Framework
theme: just-the-docs

url: https://themoenen.github.io/openad-docs

aux_links:
    Accelerate Science: https://accelerate.science/

# Carbon customization
color_scheme: ibm-light
# callouts_level: quiet # or loud
# callouts:
#     note:
#         title: Note
#         color: blue
#     highlight:
#         color: yellow
#     important:
#         title: Important
#         color: purple
#     new:
#         title: New
#         color: green
#     warning:
#         title: Warning
#         color: red
