title: %OpenAD Documentation
description: Documentation for the Accelerated Discovery Open Toolkit Framework
theme: just-the-docs

url: https://themoenen.github.io/openad-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
