title: OpenAD Docs
description: Documentation for OpenAD, the Accelerated Discovery Open Toolkit Framework
theme: just-the-docs

url: https://themoenen.github.io/openad-docs

aux_links:
  Accelerate Science: https://accelerate.science/
